# Generated by Django 4.2.5 on 2023-09-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="position",
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
